// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Motivation.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Migrations.ApplicationDb
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240220183819_FullSystemMigration")]
    partial class FullSystemMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Motivation.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Budget")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Budget = 100000m,
                            Created = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9002),
                            Name = "Главное подразделение",
                            ParentId = 1,
                            Updated = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9005)
                        });
                });

            modelBuilder.Entity("Motivation.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsManager")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PositionId")
                        .HasColumnType("integer");

                    b.Property<int>("QualificationId")
                        .HasColumnType("integer");

                    b.Property<int>("RankId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PositionId");

                    b.HasIndex("QualificationId");

                    b.HasIndex("RankId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9534),
                            DepartmentId = 1,
                            Email = "ivan@test.ru",
                            EndTime = new DateTime(1, 1, 1, 15, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Иван",
                            IsManager = true,
                            LastName = "Иванов",
                            MiddleName = "Иванович",
                            Photo = "/images/profile.png",
                            PositionId = 1,
                            QualificationId = 1,
                            RankId = 1,
                            StartTime = new DateTime(1, 1, 1, 6, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            Updated = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9534),
                            UserId = ""
                        });
                });

            modelBuilder.Entity("Motivation.Models.EmployeePenalty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PenaltyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PenaltyId");

                    b.ToTable("EmployeePenalties");
                });

            modelBuilder.Entity("Motivation.Models.EmployeeTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Ended")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Started")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeTasks");
                });

            modelBuilder.Entity("Motivation.Models.Penalty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("PositionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("Penalties");
                });

            modelBuilder.Entity("Motivation.Models.PointOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PointsOfInterest");
                });

            modelBuilder.Entity("Motivation.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Salary")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9007),
                            Name = "Менеджер",
                            Salary = 1000m,
                            Updated = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9008)
                        });
                });

            modelBuilder.Entity("Motivation.Models.Qualification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("PositionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("Qualifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9254),
                            Name = "Низкая",
                            Points = 0,
                            PositionId = 1,
                            Updated = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9254)
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9274),
                            Name = "Средняя",
                            Points = 10,
                            PositionId = 1,
                            Updated = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9274)
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9282),
                            Name = "Высокая",
                            Points = 20,
                            PositionId = 1,
                            Updated = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9283)
                        });
                });

            modelBuilder.Entity("Motivation.Models.Rank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<int>("PositionId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SalaryBonus")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("Ranks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9344),
                            Number = 1,
                            PositionId = 1,
                            SalaryBonus = 100m,
                            Updated = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9344)
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9364),
                            Number = 2,
                            PositionId = 1,
                            SalaryBonus = 100m,
                            Updated = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9364)
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9372),
                            Number = 3,
                            PositionId = 1,
                            SalaryBonus = 100m,
                            Updated = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9373)
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9380),
                            Number = 4,
                            PositionId = 1,
                            SalaryBonus = 100m,
                            Updated = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9380)
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9387),
                            Number = 5,
                            PositionId = 1,
                            SalaryBonus = 100m,
                            Updated = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9388)
                        },
                        new
                        {
                            Id = 6,
                            Created = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9397),
                            Number = 6,
                            PositionId = 1,
                            SalaryBonus = 100m,
                            Updated = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9397)
                        },
                        new
                        {
                            Id = 7,
                            Created = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9405),
                            Number = 7,
                            PositionId = 1,
                            SalaryBonus = 100m,
                            Updated = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9405)
                        },
                        new
                        {
                            Id = 8,
                            Created = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9412),
                            Number = 8,
                            PositionId = 1,
                            SalaryBonus = 100m,
                            Updated = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9412)
                        },
                        new
                        {
                            Id = 9,
                            Created = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9419),
                            Number = 9,
                            PositionId = 1,
                            SalaryBonus = 100m,
                            Updated = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9419)
                        },
                        new
                        {
                            Id = 10,
                            Created = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9427),
                            Number = 10,
                            PositionId = 1,
                            SalaryBonus = 100m,
                            Updated = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9428)
                        },
                        new
                        {
                            Id = 11,
                            Created = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9435),
                            Number = 11,
                            PositionId = 1,
                            SalaryBonus = 100m,
                            Updated = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9435)
                        });
                });

            modelBuilder.Entity("Motivation.Models.ScoreSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CalculatedRankId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Efficiency")
                        .HasColumnType("integer");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndPeriod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsSigned")
                        .HasColumnType("boolean");

                    b.Property<int>("NewRankId")
                        .HasColumnType("integer");

                    b.Property<double>("PenaltyPoints")
                        .HasColumnType("double precision");

                    b.Property<int>("QualificationId")
                        .HasColumnType("integer");

                    b.Property<int>("RankId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Salary")
                        .HasColumnType("numeric");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("ShiftsCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartPeriod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WorkingTime")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CalculatedRankId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("NewRankId");

                    b.HasIndex("QualificationId");

                    b.HasIndex("RankId");

                    b.ToTable("ScoreSheets");
                });

            modelBuilder.Entity("Motivation.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Ended")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastPauseStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LegalEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LegalStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("PauseTime")
                        .HasColumnType("interval");

                    b.Property<DateTime>("Started")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Shifts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9575),
                            EmployeeId = 1,
                            Ended = new DateTime(2024, 2, 1, 15, 0, 0, 0, DateTimeKind.Utc),
                            LastPauseStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LegalEndTime = new DateTime(1, 1, 1, 15, 0, 0, 0, DateTimeKind.Utc),
                            LegalStartTime = new DateTime(1, 1, 1, 6, 0, 0, 0, DateTimeKind.Utc),
                            PauseTime = new TimeSpan(0, 0, 0, 0, 0),
                            Started = new DateTime(2024, 2, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9575)
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9595),
                            EmployeeId = 1,
                            Ended = new DateTime(2024, 2, 2, 15, 0, 0, 0, DateTimeKind.Utc),
                            LastPauseStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LegalEndTime = new DateTime(1, 1, 1, 15, 0, 0, 0, DateTimeKind.Utc),
                            LegalStartTime = new DateTime(1, 1, 1, 6, 0, 0, 0, DateTimeKind.Utc),
                            PauseTime = new TimeSpan(0, 0, 0, 0, 0),
                            Started = new DateTime(2024, 2, 2, 5, 0, 0, 0, DateTimeKind.Utc),
                            Updated = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9595)
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9607),
                            EmployeeId = 1,
                            Ended = new DateTime(2024, 2, 5, 16, 0, 0, 0, DateTimeKind.Utc),
                            LastPauseStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LegalEndTime = new DateTime(1, 1, 1, 15, 0, 0, 0, DateTimeKind.Utc),
                            LegalStartTime = new DateTime(1, 1, 1, 6, 0, 0, 0, DateTimeKind.Utc),
                            PauseTime = new TimeSpan(0, 0, 0, 0, 0),
                            Started = new DateTime(2024, 2, 5, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9607)
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9617),
                            EmployeeId = 1,
                            Ended = new DateTime(2024, 2, 6, 16, 0, 0, 0, DateTimeKind.Utc),
                            LastPauseStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LegalEndTime = new DateTime(1, 1, 1, 15, 0, 0, 0, DateTimeKind.Utc),
                            LegalStartTime = new DateTime(1, 1, 1, 6, 0, 0, 0, DateTimeKind.Utc),
                            PauseTime = new TimeSpan(0, 0, 0, 0, 0),
                            Started = new DateTime(2024, 2, 6, 6, 0, 0, 0, DateTimeKind.Utc),
                            Updated = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9617)
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9627),
                            EmployeeId = 1,
                            Ended = new DateTime(2024, 2, 7, 14, 0, 0, 0, DateTimeKind.Utc),
                            LastPauseStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LegalEndTime = new DateTime(1, 1, 1, 15, 0, 0, 0, DateTimeKind.Utc),
                            LegalStartTime = new DateTime(1, 1, 1, 6, 0, 0, 0, DateTimeKind.Utc),
                            PauseTime = new TimeSpan(0, 0, 0, 0, 0),
                            Started = new DateTime(2024, 2, 7, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9627)
                        },
                        new
                        {
                            Id = 6,
                            Created = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9637),
                            EmployeeId = 1,
                            Ended = new DateTime(2024, 2, 8, 16, 0, 0, 0, DateTimeKind.Utc),
                            LastPauseStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LegalEndTime = new DateTime(1, 1, 1, 15, 0, 0, 0, DateTimeKind.Utc),
                            LegalStartTime = new DateTime(1, 1, 1, 6, 0, 0, 0, DateTimeKind.Utc),
                            PauseTime = new TimeSpan(0, 0, 0, 0, 0),
                            Started = new DateTime(2024, 2, 8, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9638)
                        },
                        new
                        {
                            Id = 7,
                            Created = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9647),
                            EmployeeId = 1,
                            Ended = new DateTime(2024, 2, 9, 14, 0, 0, 0, DateTimeKind.Utc),
                            LastPauseStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LegalEndTime = new DateTime(1, 1, 1, 15, 0, 0, 0, DateTimeKind.Utc),
                            LegalStartTime = new DateTime(1, 1, 1, 6, 0, 0, 0, DateTimeKind.Utc),
                            PauseTime = new TimeSpan(0, 0, 0, 0, 0),
                            Started = new DateTime(2024, 2, 9, 6, 0, 0, 0, DateTimeKind.Utc),
                            Updated = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9647)
                        },
                        new
                        {
                            Id = 8,
                            Created = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9658),
                            EmployeeId = 1,
                            Ended = new DateTime(2024, 2, 12, 16, 0, 0, 0, DateTimeKind.Utc),
                            LastPauseStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LegalEndTime = new DateTime(1, 1, 1, 15, 0, 0, 0, DateTimeKind.Utc),
                            LegalStartTime = new DateTime(1, 1, 1, 6, 0, 0, 0, DateTimeKind.Utc),
                            PauseTime = new TimeSpan(0, 0, 0, 0, 0),
                            Started = new DateTime(2024, 2, 12, 6, 0, 0, 0, DateTimeKind.Utc),
                            Updated = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9658)
                        },
                        new
                        {
                            Id = 9,
                            Created = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9668),
                            EmployeeId = 1,
                            Ended = new DateTime(2024, 2, 13, 15, 0, 0, 0, DateTimeKind.Utc),
                            LastPauseStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LegalEndTime = new DateTime(1, 1, 1, 15, 0, 0, 0, DateTimeKind.Utc),
                            LegalStartTime = new DateTime(1, 1, 1, 6, 0, 0, 0, DateTimeKind.Utc),
                            PauseTime = new TimeSpan(0, 0, 0, 0, 0),
                            Started = new DateTime(2024, 2, 13, 8, 0, 0, 0, DateTimeKind.Utc),
                            Updated = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9668)
                        },
                        new
                        {
                            Id = 10,
                            Created = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9679),
                            EmployeeId = 1,
                            Ended = new DateTime(2024, 2, 14, 15, 0, 0, 0, DateTimeKind.Utc),
                            LastPauseStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LegalEndTime = new DateTime(1, 1, 1, 15, 0, 0, 0, DateTimeKind.Utc),
                            LegalStartTime = new DateTime(1, 1, 1, 6, 0, 0, 0, DateTimeKind.Utc),
                            PauseTime = new TimeSpan(0, 0, 0, 0, 0),
                            Started = new DateTime(2024, 2, 14, 7, 0, 0, 0, DateTimeKind.Utc),
                            Updated = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9679)
                        },
                        new
                        {
                            Id = 11,
                            Created = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9689),
                            EmployeeId = 1,
                            Ended = new DateTime(2024, 2, 15, 15, 0, 0, 0, DateTimeKind.Utc),
                            LastPauseStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LegalEndTime = new DateTime(1, 1, 1, 15, 0, 0, 0, DateTimeKind.Utc),
                            LegalStartTime = new DateTime(1, 1, 1, 6, 0, 0, 0, DateTimeKind.Utc),
                            PauseTime = new TimeSpan(0, 0, 0, 0, 0),
                            Started = new DateTime(2024, 2, 15, 6, 0, 0, 0, DateTimeKind.Utc),
                            Updated = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9689)
                        },
                        new
                        {
                            Id = 12,
                            Created = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9761),
                            EmployeeId = 1,
                            Ended = new DateTime(2024, 2, 16, 15, 0, 0, 0, DateTimeKind.Utc),
                            LastPauseStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LegalEndTime = new DateTime(1, 1, 1, 15, 0, 0, 0, DateTimeKind.Utc),
                            LegalStartTime = new DateTime(1, 1, 1, 6, 0, 0, 0, DateTimeKind.Utc),
                            PauseTime = new TimeSpan(0, 0, 0, 0, 0),
                            Started = new DateTime(2024, 2, 16, 7, 0, 0, 0, DateTimeKind.Utc),
                            Updated = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9762)
                        },
                        new
                        {
                            Id = 13,
                            Created = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9776),
                            EmployeeId = 1,
                            Ended = new DateTime(2024, 2, 19, 14, 0, 0, 0, DateTimeKind.Utc),
                            LastPauseStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LegalEndTime = new DateTime(1, 1, 1, 15, 0, 0, 0, DateTimeKind.Utc),
                            LegalStartTime = new DateTime(1, 1, 1, 6, 0, 0, 0, DateTimeKind.Utc),
                            PauseTime = new TimeSpan(0, 0, 0, 0, 0),
                            Started = new DateTime(2024, 2, 19, 5, 0, 0, 0, DateTimeKind.Utc),
                            Updated = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9776)
                        },
                        new
                        {
                            Id = 14,
                            Created = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9785),
                            EmployeeId = 1,
                            Ended = new DateTime(2024, 2, 20, 14, 0, 0, 0, DateTimeKind.Utc),
                            LastPauseStart = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LegalEndTime = new DateTime(1, 1, 1, 15, 0, 0, 0, DateTimeKind.Utc),
                            LegalStartTime = new DateTime(1, 1, 1, 6, 0, 0, 0, DateTimeKind.Utc),
                            PauseTime = new TimeSpan(0, 0, 0, 0, 0),
                            Started = new DateTime(2024, 2, 20, 7, 0, 0, 0, DateTimeKind.Utc),
                            Updated = new DateTime(2024, 2, 20, 18, 38, 19, 525, DateTimeKind.Utc).AddTicks(9786)
                        });
                });

            modelBuilder.Entity("Motivation.Models.ShiftRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("ShiftRules");
                });

            modelBuilder.Entity("Motivation.Models.Department", b =>
                {
                    b.HasOne("Motivation.Models.Department", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Motivation.Models.Employee", b =>
                {
                    b.HasOne("Motivation.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Motivation.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Motivation.Models.Qualification", "Qualification")
                        .WithMany()
                        .HasForeignKey("QualificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Motivation.Models.Rank", "Rank")
                        .WithMany()
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Position");

                    b.Navigation("Qualification");

                    b.Navigation("Rank");
                });

            modelBuilder.Entity("Motivation.Models.EmployeePenalty", b =>
                {
                    b.HasOne("Motivation.Models.Employee", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Motivation.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Motivation.Models.Penalty", "Penalty")
                        .WithMany()
                        .HasForeignKey("PenaltyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Employee");

                    b.Navigation("Penalty");
                });

            modelBuilder.Entity("Motivation.Models.EmployeeTask", b =>
                {
                    b.HasOne("Motivation.Models.Employee", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Motivation.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Motivation.Models.Penalty", b =>
                {
                    b.HasOne("Motivation.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Motivation.Models.Qualification", b =>
                {
                    b.HasOne("Motivation.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Motivation.Models.Rank", b =>
                {
                    b.HasOne("Motivation.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Motivation.Models.ScoreSheet", b =>
                {
                    b.HasOne("Motivation.Models.Rank", "CalculatedRank")
                        .WithMany()
                        .HasForeignKey("CalculatedRankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Motivation.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Motivation.Models.Rank", "NewRank")
                        .WithMany()
                        .HasForeignKey("NewRankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Motivation.Models.Qualification", "Qualification")
                        .WithMany()
                        .HasForeignKey("QualificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Motivation.Models.Rank", "Rank")
                        .WithMany()
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalculatedRank");

                    b.Navigation("Employee");

                    b.Navigation("NewRank");

                    b.Navigation("Qualification");

                    b.Navigation("Rank");
                });

            modelBuilder.Entity("Motivation.Models.Shift", b =>
                {
                    b.HasOne("Motivation.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Motivation.Models.ShiftRule", b =>
                {
                    b.HasOne("Motivation.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Motivation.Models.Department", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
